setwd('~/Github/postdoc/tradeoff/docs')
suppressMessages(knit('t1_results_knit_.md'))
suppressMessages(knit('t2_results_knit_.md'))
suppressMessages(knit('t3_results_knit_.md'))
system('pandoc t1_results.md -o t1_results.pdf')
system('pandoc t2_results.md -o t2_results.pdf')
system('pandoc t3_results.md -o t3_results.pdf')
# system('open -a Preview results.pdf')
setwd('~/Github/postdoc/tradeoff/')
